apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}  # Name of the service from values.yaml
  labels:
    app: {{ .Values.deployment.name }}  # Label for the application
spec:
  type: {{ .Values.service.type }}  # Type of the service (ClusterIP, NodePort, LoadBalancer)
  ports:
    - port: {{ .Values.service.port }}  # Port to expose the service
      targetPort: 80  # Target port on the container
  selector:
    app: {{ .Values.deployment.name }}  # Selector label for the application name
