apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appConfig.name }}
  labels:
    app: {{ .Values.appConfig.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.appConfig.name }}



#####Working file ####

#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "nginx-app.fullname" . }}
#  labels:
#    app: {{ include "nginx-app.name" . }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: 8080
#  selector:
#    app: {{ include "nginx-app.name" . }}
